//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("MMLibraryModel", "BookBookInfo", "Book", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MMLibrarySystem.EntityModel.Book), "BookInfo", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(MMLibrarySystem.EntityModel.BookInfo), true)]

#endregion

namespace MMLibrarySystem.EntityModel
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class MMLibraryModelContainer : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new MMLibraryModelContainer object using the connection string found in the 'MMLibraryModelContainer' section of the application configuration file.
        /// </summary>
        public MMLibraryModelContainer() : base("name=MMLibraryModelContainer", "MMLibraryModelContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new MMLibraryModelContainer object.
        /// </summary>
        public MMLibraryModelContainer(string connectionString) : base(connectionString, "MMLibraryModelContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new MMLibraryModelContainer object.
        /// </summary>
        public MMLibraryModelContainer(EntityConnection connection) : base(connection, "MMLibraryModelContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Book> Books
        {
            get
            {
                if ((_Books == null))
                {
                    _Books = base.CreateObjectSet<Book>("Books");
                }
                return _Books;
            }
        }
        private ObjectSet<Book> _Books;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<BookInfo> BookInfoes
        {
            get
            {
                if ((_BookInfoes == null))
                {
                    _BookInfoes = base.CreateObjectSet<BookInfo>("BookInfoes");
                }
                return _BookInfoes;
            }
        }
        private ObjectSet<BookInfo> _BookInfoes;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Books EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToBooks(Book book)
        {
            base.AddObject("Books", book);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the BookInfoes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToBookInfoes(BookInfo bookInfo)
        {
            base.AddObject("BookInfoes", bookInfo);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MMLibraryModel", Name="Book")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Book : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Book object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="bookNumber">Initial value of the BookNumber property.</param>
        /// <param name="bookInfoId">Initial value of the BookInfoId property.</param>
        public static Book CreateBook(global::System.Int64 id, global::System.String bookNumber, global::System.Int64 bookInfoId)
        {
            Book book = new Book();
            book.Id = id;
            book.BookNumber = bookNumber;
            book.BookInfoId = bookInfoId;
            return book;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int64 _Id;
        partial void OnIdChanging(global::System.Int64 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String BookNumber
        {
            get
            {
                return _BookNumber;
            }
            set
            {
                OnBookNumberChanging(value);
                ReportPropertyChanging("BookNumber");
                _BookNumber = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("BookNumber");
                OnBookNumberChanged();
            }
        }
        private global::System.String _BookNumber;
        partial void OnBookNumberChanging(global::System.String value);
        partial void OnBookNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 BookInfoId
        {
            get
            {
                return _BookInfoId;
            }
            set
            {
                OnBookInfoIdChanging(value);
                ReportPropertyChanging("BookInfoId");
                _BookInfoId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("BookInfoId");
                OnBookInfoIdChanged();
            }
        }
        private global::System.Int64 _BookInfoId;
        partial void OnBookInfoIdChanging(global::System.Int64 value);
        partial void OnBookInfoIdChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MMLibraryModel", "BookBookInfo", "BookInfo")]
        public BookInfo BookInfo
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<BookInfo>("MMLibraryModel.BookBookInfo", "BookInfo").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<BookInfo>("MMLibraryModel.BookBookInfo", "BookInfo").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<BookInfo> BookInfoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<BookInfo>("MMLibraryModel.BookBookInfo", "BookInfo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<BookInfo>("MMLibraryModel.BookBookInfo", "BookInfo", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MMLibraryModel", Name="BookInfo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class BookInfo : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new BookInfo object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="tiTle">Initial value of the TiTle property.</param>
        /// <param name="description">Initial value of the Description property.</param>
        /// <param name="userAndTeam">Initial value of the UserAndTeam property.</param>
        /// <param name="publisher">Initial value of the Publisher property.</param>
        /// <param name="supplier">Initial value of the Supplier property.</param>
        /// <param name="netPrice">Initial value of the NetPrice property.</param>
        /// <param name="purchaseDate">Initial value of the PurchaseDate property.</param>
        /// <param name="requestedBy">Initial value of the RequestedBy property.</param>
        public static BookInfo CreateBookInfo(global::System.Int64 id, global::System.String tiTle, global::System.String description, global::System.String userAndTeam, global::System.String publisher, global::System.String supplier, global::System.Double netPrice, global::System.DateTime purchaseDate, global::System.String requestedBy)
        {
            BookInfo bookInfo = new BookInfo();
            bookInfo.Id = id;
            bookInfo.TiTle = tiTle;
            bookInfo.Description = description;
            bookInfo.UserAndTeam = userAndTeam;
            bookInfo.Publisher = publisher;
            bookInfo.Supplier = supplier;
            bookInfo.NetPrice = netPrice;
            bookInfo.PurchaseDate = purchaseDate;
            bookInfo.RequestedBy = requestedBy;
            return bookInfo;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int64 _Id;
        partial void OnIdChanging(global::System.Int64 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String TiTle
        {
            get
            {
                return _TiTle;
            }
            set
            {
                OnTiTleChanging(value);
                ReportPropertyChanging("TiTle");
                _TiTle = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("TiTle");
                OnTiTleChanged();
            }
        }
        private global::System.String _TiTle;
        partial void OnTiTleChanging(global::System.String value);
        partial void OnTiTleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String UserAndTeam
        {
            get
            {
                return _UserAndTeam;
            }
            set
            {
                OnUserAndTeamChanging(value);
                ReportPropertyChanging("UserAndTeam");
                _UserAndTeam = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("UserAndTeam");
                OnUserAndTeamChanged();
            }
        }
        private global::System.String _UserAndTeam;
        partial void OnUserAndTeamChanging(global::System.String value);
        partial void OnUserAndTeamChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Publisher
        {
            get
            {
                return _Publisher;
            }
            set
            {
                OnPublisherChanging(value);
                ReportPropertyChanging("Publisher");
                _Publisher = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Publisher");
                OnPublisherChanged();
            }
        }
        private global::System.String _Publisher;
        partial void OnPublisherChanging(global::System.String value);
        partial void OnPublisherChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Supplier
        {
            get
            {
                return _Supplier;
            }
            set
            {
                OnSupplierChanging(value);
                ReportPropertyChanging("Supplier");
                _Supplier = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Supplier");
                OnSupplierChanged();
            }
        }
        private global::System.String _Supplier;
        partial void OnSupplierChanging(global::System.String value);
        partial void OnSupplierChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double NetPrice
        {
            get
            {
                return _NetPrice;
            }
            set
            {
                OnNetPriceChanging(value);
                ReportPropertyChanging("NetPrice");
                _NetPrice = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NetPrice");
                OnNetPriceChanged();
            }
        }
        private global::System.Double _NetPrice;
        partial void OnNetPriceChanging(global::System.Double value);
        partial void OnNetPriceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime PurchaseDate
        {
            get
            {
                return _PurchaseDate;
            }
            set
            {
                OnPurchaseDateChanging(value);
                ReportPropertyChanging("PurchaseDate");
                _PurchaseDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PurchaseDate");
                OnPurchaseDateChanged();
            }
        }
        private global::System.DateTime _PurchaseDate;
        partial void OnPurchaseDateChanging(global::System.DateTime value);
        partial void OnPurchaseDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String RequestedBy
        {
            get
            {
                return _RequestedBy;
            }
            set
            {
                OnRequestedByChanging(value);
                ReportPropertyChanging("RequestedBy");
                _RequestedBy = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("RequestedBy");
                OnRequestedByChanged();
            }
        }
        private global::System.String _RequestedBy;
        partial void OnRequestedByChanging(global::System.String value);
        partial void OnRequestedByChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MMLibraryModel", "BookBookInfo", "Book")]
        public EntityCollection<Book> Books
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Book>("MMLibraryModel.BookBookInfo", "Book");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Book>("MMLibraryModel.BookBookInfo", "Book", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
